### ISSUE TITLE
Build errors from first build

### ISSUE THREAD

**Issue by KevinAtDesignworx** [extropic/adventure#1]
[khughes@localhost adventure]$ plz build
Building [17/141, 1.9s]:
Build stopped after 8.71s. 3 targets failed:
    //third_party/miniupnpc:__miniupnpc#lib#connecthostport_c
Error building target //third_party/miniupnpc:__miniupnpc#lib#connecthostport_c: exit status 1
third_party/miniupnpc/connecthostport.c: In function ‘connecthostport’:
third_party/miniupnpc/connecthostport.c, line 74, column 18: error: storage size of ‘hints’ isn’t known
  struct addrinfo hints;
                  ^
third_party/miniupnpc/connecthostport.c, line 174, column 2: warning: implicit declaration of function ‘getaddrinfo’ [-Wimplicit-function-declaration]
  n = getaddrinfo(tmp_host, port_str, &hints, &ai);
  ^
third_party/miniupnpc/connecthostport.c, line 180, column 3: warning: implicit declaration of function ‘gai_strerror’ [-Wimplicit-function-declaration]
   fprintf(stderr, "getaddrinfo() error : %s\n", gai_strerror(n));
   ^
third_party/miniupnpc/connecthostport.c, line 180, column 3: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
third_party/miniupnpc/connecthostport.c, line 185, column 22: error: dereferencing pointer to incomplete type
  for(p = ai; p; p = p->ai_next)
                      ^
third_party/miniupnpc/connecthostport.c, line 187, column 15: error: dereferencing pointer to incomplete type
   s = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
               ^
third_party/miniupnpc/connecthostport.c, line 187, column 29: error: dereferencing pointer to incomplete type
   s = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
                             ^
third_party/miniupnpc/connecthostport.c, line 187, column 45: error: dereferencing pointer to incomplete type
   s = socket(p->ai_family, p->ai_socktype, p->ai_protocol);
                                             ^
third_party/miniupnpc/connecthostport.c, line 190, column 7: error: dereferencing pointer to incomplete type
   if(p->ai_addr->sa_family == AF_INET6 && scope_id > 0) {
       ^
third_party/miniupnpc/connecthostport.c, line 191, column 58: error: dereferencing pointer to incomplete type
    struct sockaddr_in6 * addr6 = (struct sockaddr_in6 *)p->ai_addr;
                                                          ^
third_party/miniupnpc/connecthostport.c, line 209, column 19: error: dereferencing pointer to incomplete type
   n = connect(s, p->ai_addr, p->ai_addrlen);
                   ^
third_party/miniupnpc/connecthostport.c, line 209, column 31: error: dereferencing pointer to incomplete type
   n = connect(s, p->ai_addr, p->ai_addrlen);
                               ^
third_party/miniupnpc/connecthostport.c, line 229, column 5: warning: implicit declaration of function ‘freeaddrinfo’ [-Wimplicit-function-declaration]
     freeaddrinfo(ai);
     ^
third_party/miniupnpc/connecthostport.c, line 74, column 18: warning: unused variable ‘hints’ [-Wunused-variable]
  struct addrinfo hints;
                  ^

    //third_party/miniupnpc:__miniupnpc#lib#miniwget_c
Error building target //third_party/miniupnpc:__miniupnpc#lib#miniwget_c: exit status 1
third_party/miniupnpc/miniwget.c: In function ‘miniwget3’:
third_party/miniupnpc/miniwget.c, line 423, column 4: warning: implicit declaration of function ‘getnameinfo’ [-Wimplicit-function-declaration]
    n = getnameinfo((const struct sockaddr *)&saddr, saddrlen,
    ^
third_party/miniupnpc/miniwget.c, line 426, column 20: error: ‘NI_NUMERICHOST’ undeclared (first use in this function)
                    NI_NUMERICHOST | NI_NUMERICSERV);
                    ^
third_party/miniupnpc/miniwget.c, line 426, column 20: note: each undeclared identifier is reported only once for each function it appears in
third_party/miniupnpc/miniwget.c, line 426, column 37: error: ‘NI_NUMERICSERV’ undeclared (first use in this function)
                    NI_NUMERICHOST | NI_NUMERICSERV);
                                     ^
third_party/miniupnpc/miniwget.c, line 431, column 5: warning: implicit declaration of function ‘gai_strerror’ [-Wimplicit-function-declaration]
     fprintf(stderr, "getnameinfo() failed : %s\n", gai_strerror(n));
     ^
third_party/miniupnpc/miniwget.c, line 431, column 5: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]

    //third_party/miniupnpc:__miniupnpc#lib#minissdpc_c
Error building target //third_party/miniupnpc:__miniupnpc#lib#minissdpc_c: exit status 1
third_party/miniupnpc/minissdpc.c: In function ‘ssdpDiscoverDevices’:
third_party/miniupnpc/minissdpc.c, line 499, column 18: error: storage size of ‘hints’ isn’t known
  struct addrinfo hints, *servinfo, *p;
                  ^
third_party/miniupnpc/minissdpc.c, line 665, column 21: error: storage size of ‘reqn’ isn’t known
     struct ip_mreqn reqn; /* only defined with -D_BSD_SOURCE or -D_GNU_SOURCE */
                     ^
third_party/miniupnpc/minissdpc.c, line 666, column 29: error: invalid application of ‘sizeof’ to incomplete type ‘struct ip_mreqn’
     memset(&reqn, 0, sizeof(struct ip_mreqn));
                             ^
third_party/miniupnpc/minissdpc.c, line 665, column 21: warning: unused variable ‘reqn’ [-Wunused-variable]
     struct ip_mreqn reqn; /* only defined with -D_BSD_SOURCE or -D_GNU_SOURCE */
                     ^
third_party/miniupnpc/minissdpc.c, line 769, column 3: warning: implicit declaration of function ‘getaddrinfo’ [-Wimplicit-function-declaration]
   if ((rv = getaddrinfo(ipv6
   ^
third_party/miniupnpc/minissdpc.c, line 778, column 4: warning: implicit declaration of function ‘gai_strerror’ [-Wimplicit-function-declaration]
    fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(rv));
    ^
third_party/miniupnpc/minissdpc.c, line 778, column 4: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
third_party/miniupnpc/minissdpc.c, line 782, column 29: error: dereferencing pointer to incomplete type
   for(p = servinfo; p; p = p->ai_next) {
                             ^
third_party/miniupnpc/minissdpc.c, line 783, column 34: error: dereferencing pointer to incomplete type
    n = sendto(sudp, bufr, n, 0, p->ai_addr, p->ai_addrlen);
                                  ^
third_party/miniupnpc/minissdpc.c, line 783, column 46: error: dereferencing pointer to incomplete type
    n = sendto(sudp, bufr, n, 0, p->ai_addr, p->ai_addrlen);
                                              ^
third_party/miniupnpc/minissdpc.c, line 798, column 3: warning: implicit declaration of function ‘freeaddrinfo’ [-Wimplicit-function-declaration]
   freeaddrinfo(servinfo);
   ^
third_party/miniupnpc/minissdpc.c, line 499, column 18: warning: unused variable ‘hints’ [-Wunused-variable]
  struct addrinfo hints, *servinfo, *p;
                  ^

[khughes@localhost adventure]$

**Comment by jasongpearce** [comment]
Added compile-time predefines expected to be present on linux for the miniupnpc module.
